---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install unzip package
    apt: name=unzip state=present
  - name: install xvfb package
    apt: name=xvfb state=present
  - name: install libxi6 package
    apt: name=libxi6 state=present
  - name: install libgconf-2-4 package
    apt: name=libgconf-2-4 state=present
  - name: update linux signing key
    shell: curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
  - name: Add Google Chrome list
    shell: echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes
  - name: install google-chrome-stable package
    apt: name=google-chrome-stable state=present
  - name: Get Chrome Driver zip
    shell: wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
  - name: unzip the chrome driver
    shell: unzip chromedriver_linux64.zip
  - name: move chromedriver to usr bin chromedriver
    shell: mv chromedriver /usr/bin/chromedriver
  - name: Provide file owner to chrome driver
    shell: chown root:root /usr/bin/chromedriver
  - name: Provide execute permission to chrome driver
    shell: chmod +x /usr/bin/chromedriver
